# Generated by Django 4.0.2 on 2022-02-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_testmodel_alter_employee_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.IntegerField(choices=[(1, 'SoftWare Developer'), (2, 'QA Engineer'), (3, 'DevOps Specialist')], default=1, max_length=18),
            preserve_default=False,
        ),
    ]
