# Generated by Django 4.0.2 on 2022-02-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_delete_testmodel_employee_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.CharField(choices=[('SoftUni', 'SoftUni'), ('Google', 'Google')], default='SoftUni', max_length=7),
            preserve_default=False,
        ),
    ]
